### ISSUE TITLE
Failed to load the google font "Vollkorn" specified in head.html Due to using http instead of https

### ISSUE THREAD

**Issue by aelsaman** [excentris/compass#6]
Hello
thanks for the nice template, I like it. 
However, when I tried to fork and host on Github.io, The page failed to load the font from "http://fonts.googleapis.com" and I got the below error (using google chrome) :
`this page is trying to load scripts from unauthenticated sources` in a browser popup.

I updated the source code to use https instead of http in the link to google fonts and it works fine.
#7

**Comment by excentris** [comment]
Thanks for PR. Closing this.
